cppalliance/cppalliance.github.io

_posts/2019-06-10-DamiansJuneUpdate.md

Signed-off-by: Damian Jarek <damian.jarek93@gmail.com>

June update

---

_posts/2019-06-10-DamiansJuneUpdate.md

Signed-off-by: Damian Jarek <damian.jarek93@gmail.com>

Fix post title

---

_posts/2019-07-14-DamiansJulyUpdate.md

Signed-off-by: Damian Jarek <damian.jarek93@gmail.com>

July update

---

_posts/2019-08-19-DamiansAugustUpdate.md

Signed-off-by: Damian Jarek <damian.jarek93@gmail.com>

August update

---

_layouts/alumni.html
_sass/pages/homepage.scss
index.html
people/damian.html
people/jens.html
people/marshall.html

- *Please include a summary of the changes.*
* Added new homepage Alumni section based on new Alumni layout found in _layout directory. 
* 3 team members updated to be Alumni
----
----
<pre>
Task: create new Alumni section on homepage
</pre>
<pre>
1. n/a
</pre>
----
- *Provide instructions so we can reproduce.*
<pre>
Steps:
1. Tested on local and staging environments (Github pages).
</pre>

added alumni section to homepage based on new layout

---

_posts/2020-01-31-RichardsJanuaryUpdate.md

Richard 2020-jan

---

proposals.html

- Changed header text from 'Submissions' to 'Proposals'
- Adjusted the header text shadow

Proposal page updates:

---

_posts/2020-01-31-RichardsJanuaryUpdate.md
people/richard.html

Corrects typos, grammar and links in richard's BIO and jan 2020 blog entry.

Richard jan20 errata

---

.circleci/config.yml
_config_develop.yml
proposals.html

- Moved the shadow text to the left a bit
- Updated the page title to 'Proposals'

Proposal page updates 2:

---

_posts/2020-02-29-RichardsFebruaryUpdate.md

richards rebruary update

---

_posts/2020-05-08-KrystiansAprilUpdate.md

Add Krystian's April Update

---

_config.yml
_posts/2020-04-07-KrystiansMarchUpdate.md
_sass/modules/github-light.scss
_sass/pages/post.scss
css/style.scss

- Add github syntax-highlight
- blockquote formatting
- Fix ordered-list position in richard's jan update post
- Fix markdown table formatting

replicate github markdown look

---

_sass/pages/post.scss

Fixed the issue of the blog page's contents section getting narrower at a 120% zoom level

add media query for 1500px viewport

---

_posts/2020-06-31-RichardsJuneUpdate.md

Change title to May/June update

Apply errata to June update to better represent evolution of Unified Executors

---

_posts/2020-09-01-RichardsAugustUpdate.md
_posts/2020-09-30-RichardsSeptemberUpdate.md

Added final two steps.
Please merge.

2020 09 30 richard

---

_posts/2020-12-22-RichardsDecemberUpdate.md

Removed errnoneous commit rebased in from master.

Richard's November/December 2020 update

---

_posts/2021-01-01-RichardsNewYearUpdate.md

2021 Richard's New Year Blog - HTTP Connection Caching

New year 2021

---

_posts/2022-12-11-Asio201Deferred.md

@vinniefalco 
Didn't verify the examples yet, but does it make sense?

First draft for deferred post

---

_posts/2023-01-02-Asio201Timeouts.md

Not proof read, do not merge. PR for sharing with people.

Initial draft for timeout article.

---

_posts/2023-10-27-MattsQ3Update.md

@louistatta Can you please also create the #boost-decimal channel on slack? I think we are far enough along in development for that to be worthwhile. Thanks

Add Matts Q3 Update

---

_posts/2024-01-10-MattsQ4Update.md

I believe this hits all of the topics from the message in the Slack channel. Please let me know if you have any questions or comments.

Matt's 2023Q4 Update

---

index.html

- Removed the section.  Not commented out, it's in the history if we decide to add it back, but I believe if we did it would require additional changes to deal with any redundancies in language anyway.

Removed Gift Policy section

---

index.html
people/jon.html
people/louis.html
people/vinnie.html

Update team page and titles

---

_sass/base/print.scss
css/style.scss

This PR enhances the print styles for our website to ensure better readability and usability when printing. 
fixes #222

Print media selector styles

---

_posts/2025-04-08-Roberts2025Q1Update.md
people/robert.html

Updated my profile and added a blog post for Q1

robs profile and blog post

---

_posts/2025-10-06-Matts2025Q3Update.md

Once the review period opens I plan to point the ML to this so that they can see what's changed since January.

Add matt's 2025Q3 update
